@IsTest
/**
*@author Jaunbocus Muhammad Irshaad
*@Date Creation 22/12/2021
*@Date modification 
*@description 
*/
public class AP01_FreightRateRequestTriggerHanderTEST {
    @isTest static void testMapResponsibleParty() {
        TestDataFactory.testMapResponsibleParty();
    }
    @isTest static void testMapResponsibleParty2() {
        TestDataFactory.testMapResponsibleParty2();
    }
    @isTest static void testMapResponsibleParty3() {
        TestDataFactory.testMapResponsibleParty3();
    }

}